{% set version = "1.0.410" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinymanager
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinymanager_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinymanager/shinymanager_{{ version }}.tar.gz
  sha256: b6cd31149aaffd81d181a0c2f19eee8963b32912b3df1149e56448fe9a38865a

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-dbi
    - r-dt >=0.5
    - r-r.utils
    - r-r6
    - r-rsqlite
    - r-billboarder
    - r-htmltools
    - r-openssl
    - r-scrypt
    - r-shiny

  run:
    - r-base
    - r-dbi
    - r-dt >=0.5
    - r-r.utils
    - r-r6
    - r-rsqlite
    - r-billboarder
    - r-htmltools
    - r-openssl
    - r-scrypt
    - r-shiny

test:
  commands:
    - $R -e "library('shinymanager')"           # [not win]
    - "\"%R%\" -e \"library('shinymanager')\""  # [win]

about:
  home: https://github.com/datastorm-open/shinymanager

  license: GPL-3.0-only
  summary: Simple and secure authentification mechanism for single 'Shiny' applications. Credentials are stored in an encrypted 'SQLite' database. Source code of main application is protected until authentication is successful.

  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - tdido
